spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: junsu
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
