spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: junsu
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
